### ISSUE TITLE
Question about your training details

### ISSUE THREAD

**Issue by nupnup-goddamn** [kirillProkofiev/light-weight-face-anti-spoofing#16]
May i know how many epochs did you trained for the final model based on MN3 trained on celebA_spoof and tested on LCC_FASD?

Is Max Epoch == 71 the optimum number of epochs you had tried and derived? 

Thank You

**Comment by kprokofi** [comment]
Yep, 71 is the appropriate number of epochs to train Mobilenet on this data

**Comment by nupnup-goddamn** [comment]
Thank you! Thanks for sharing this project btw! Its awesome😊👍
