### ISSUE TITLE
hi ,I test your model,find your model is not acuuracy

### ISSUE THREAD

**Issue by anthonyyuan** [kirillProkofiev/light-weight-face-anti-spoofing#6]
hi:
   I find your FRR is big,most real face is detected fake,Can u give a good model

**Comment by kirillProkofiev** [comment]
Hello,
Could you describe the problem and give me more details? 
Which model did you test and how did you do it? If the problem was in the demo,  I would be grateful, if you could send me a short video with the problem on my email: k.a.prokofiev@yandex.ru
